repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.5
    hooks:
      # Run the linter and fixer.
      - id: ruff
        types: [ python ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types: [ python ]

-   repo: local
    hooks:
      - id: pyright
        name: Pyright type checking
        entry: pyright src/
        language: system
        types: [python]
