services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_support_system
      - INIT_BASE_DATA=${INIT_BASE_DATA:-false}
    volumes:
      - .:/app
    command: >
      bash -c "
        ./install.sh
      "

  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_support_system
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_support_system"]
      interval: 5s
      timeout: 5s
      retries: 5
    entrypoint: ["docker-entrypoint.sh"]
    command: postgres -c 'max_connections=1000'

volumes:
  postgres_data:
